stages:
  - test
  - build
  - deploy
  - notify

variables:
  SLD: "test-wwww"
  TEST_PHP_IP: "127.0.0.1"
  SRC_PATH: "dist/"
  TEST_IMAGE: registry.cn-shenzhen.aliyuncs.com/xxx-dev/xxx-xxxx:$CI_COMMIT_REF_NAME-${CI_COMMIT_SHORT_SHA}    
  RELEASE_IMAGE: registry.cn-shenzhen.aliyuncs.com/xxx-dev/xx-xxx::latest  


cache:
  key: 'node_modules'  
  paths:
    - node_modules/
    - package-lock.json


before_script:
  - git checkout -f "$CI_COMMIT_REF_NAME"
  - git reset --hard origin/"$CI_COMMIT_REF_NAME"
  - yarn install 

# 客户端 k8s
build_image:
  stage: deploy
  variables:
    SLD: "dev-xxx"   
  script:
    - npm run build:dev
    - docker build -t $TEST_IMAGE .
    - echo -n $CI_REGISTRY_PASSWORD | docker login --username=$CI_REGISTRY_USER --password-stdin registry.cn-shenzhen.aliyuncs.com
    - docker push $TEST_IMAGE
    - envsubst < k8s/deploy.yaml > k8s/deployment-${CI_JOB_NAME}.yaml
    - envsubst < k8s/svc.yaml > k8s/svc-${CI_JOB_NAME}.yaml
    - envsubst < k8s/ingress.yaml  > k8s/ingress-${CI_JOB_NAME}.yaml
    - kubectl apply -f k8s/deployment-${CI_JOB_NAME}.yaml    
    - kubectl apply -f k8s/svc-${CI_JOB_NAME}.yaml,k8s/ingress-${CI_JOB_NAME}.yaml 
  environment:
    name: k8s-dev-xxxprojetname
    # action: prepare
    url: http://$SLD.demo.com    
  only:
    - dev
  tags:
    - local-runner 




job-deploy-uat-xxx:
  stage: deploy
  cache:
    key: 'node_modules'
    policy: pull
    paths:
      - node_modules/
      - package-lock.json
  variables:
    SLD: "uat-md"   
    TEST_PHP_IP: "172.16.xxx.xxx"     
  script:
    # - npm run uat
    - npm run build:uat
    - TIME_FLAG=`date +"%Y%m%d%H%M%S"`
    - ssh deployer@$TEST_PHP_IP "mkdir -p /www/wwwroot/$SLD.demo.com/releases"
    - scp -r $SRC_PATH deployer@$TEST_PHP_IP:/www/wwwroot/$SLD.demo.com/releases/$TIME_FLAG
    - ssh deployer@$TEST_PHP_IP "ln -nfs /www/wwwroot/$SLD.demo.com/releases/$TIME_FLAG /www/wwwroot/$SLD.demo.com/current"
    - echo "finish deploy-test stage"
  environment:
    name: uat-xxx
    # action: prepare
    url: http://$SLD.demo.com    
  only:
    - uat
  when:
    manual  
  tags:
    - al-git-runner

